import data from '../data/flights.json';

/**
 * data/flights.json is generated by scripts/build-data.mjs (predev/prebuild)
 * from the private flight log. It is bundled into the server build, so there
 * is no database, no native module, and no filesystem access at request time.
 */
export function getAirports() {
  return data.airports;
}

export function getFlights() {
  return data.flights;
}

export function getCountries() {
  return data.countries;
}

export function getAirlines() {
  return data.airlines;
}
